---
- name: Recover from SteamOS update
  hosts: localhost
  remote_user: deck
  become: yes

  tasks:
  - name: Check SteamOS Read Only Status
    ansible.builtin.command:
      cmd: steamos-readonly status
    ignore_errors: yes
    register: readonly_cmd

  - name: Set Fact for SteamOS Ready Only
    ansible.builtin.set_fact:
      steamosro: "{{ readonly_cmd.stdout }}"

  - name: Recover after Update
    block:
    - name: Change to RW file system
      ansible.builtin.command:
        cmd: steamos-readonly disable

    - name: Pacman Key Init
      ansible.builtin.command:
        cmd: pacman-key --init

    - name: Pacman Key Populate
      ansible.builtin.command:
        cmd: pacman-key --populate archlinux
    when: steamosro == 'enabled'

  - name: Ensure packages are installed
    community.general.pacman:
      name:
        - terraform
        - packer
        - podman
        - tmux
        - code
        - fuse-overlayfs
        - slirp4netns
      state: present

  - name: Rootless Podman
    block:
      # - name: Set unprivileged usrns clone
      #   ansible.posix.sysctl:
      #     name: kernel.unprivileged_userns_clone
      #     value: '1'
      #     sysctl_set: yes
      - name: Ensure subuid and subgid files are populated with the deck user
        ansible.builtin.copy:
          dest: "{{ item }}"
          content: |
            deck:100000:65536
        with_items:
        - /etc/subuid
        - /etc/subgid
